### ISSUE TITLE
Warnings from libffi

### ISSUE THREAD

**Issue by sigsbeym** [623637646/SwiftHook#11]
<img width="854" alt="Screenshot 2023-09-21 at 8 42 28 PM" src="https://github.com/623637646/SwiftHook/assets/86621363/e65f9489-2ec6-4aa6-872d-f00d527ef187">

I tried submitting a PR to your libffi library, but I can't.

**Comment by 623637646** [comment]
Hi @sigsbeym , May I know what your PR is for?

**Comment by sigsbeym** [comment]
Hey!
@623637646 
I was just trying to update from the parent repo.  I was hoping it would resolve the warnings.

**Comment by 623637646** [comment]
Hi  @sigsbeym  , I see. Actually, I use a fork of libffi:  https://github.com/623637646/libffi/tree/release/iOS
There are some changes to support iOS using libffi. I remember I spend a lot of time to make it work. Upgrading libffi is not an easy job. If it works fine, just with some warnings. Just let it go and your life will be easier.

**Comment by 623637646** [comment]
If you use cocoapods, this may help you to ignore the warning. https://stackoverflow.com/questions/13208202/ignore-xcode-warnings-when-using-cocoapods

**Comment by 623637646** [comment]
hi @sigsbeym 
Just upgrade libffi to the newest version 3.4.4. 
https://github.com/623637646/libffi/tree/release/iOS_3.4.4
Seems the warning is still there.
