### ISSUE TITLE
iOS build breaks with new Version of libffi (libffi_apple)

### ISSUE THREAD

**Issue by DanielKuhn** [623637646/SwiftHook#13]
After updating the CocoaPods-dependency to 3.5.0 my build breaks because `libffi_apple` can not find `cstdlib`
![image001](https://github.com/623637646/SwiftHook/assets/16227674/3bbd7168-015d-48c2-9978-e559ec61cc76)

Any help would be appreciated.

**Comment by 623637646** [comment]
hi @DanielKuhn , I saw your screenshot. The error seems to come from `Flipper-Folly`. I double check that `libffi-apple` doesn't use `cstdlib`.
Please let me know if you are sure that SwiftHook is not compatible with `Flipper`. Providing a demo project would be appreciated.

**Comment by DanielKuhn** [comment]
@623637646 Yes, you're right. But the error only comes up after updating to 3.5.0. 
It wasn't a problem with the `libffi-iOS`-dependency in 3.4.4 and I can't figure out the reason.

**Comment by DanielKuhn** [comment]
Judging from the screenshot it seems that `libffi_apple` includes [`Stdlib.h`](https://github.com/facebook/folly/blob/main/folly/portability/Stdlib.h) from Facebook/Folly during compilation, instead of Apple's native `stdlib.h`. @623637646 do you have any idea what might have caused this change from `libffi-iOS`?

**Comment by 623637646** [comment]
Good point @DanielKuhn , Probably due to the code `#include "stdlib.h"`, I would try changing it to `#include <stdlib.h>` then take a look.

**Comment by DanielKuhn** [comment]
I created a demo project to illustrate the issue: https://github.com/DanielKuhn/libffi-stdlib-demo
It consists of a blank react native project created with create-react-native-app. The basic app ([initial commit](https://github.com/DanielKuhn/libffi-stdlib-demo/commit/877400d5489ff7672ed033788f685aa473458d7a)) runs fine in the iOS Simulator. Once I install the `EasySwiftHook`-pod ([second commit](https://github.com/DanielKuhn/libffi-stdlib-demo/commit/c1b5761531e4fab468374cfa00fef78bcc7d05c8)) I get the include error, this time from `RCT-Folly`, but same problem:
![Bildschirmfoto 2024-03-14 um 11 34 26](https://github.com/623637646/SwiftHook/assets/16227674/2259aa64-a473-4b00-b3ec-6fe8677cbd09)

**Comment by DanielKuhn** [comment]
For everyone also encountering this problem: I found a workaround via a post-install hook for `libffi_apple`: https://github.com/DanielKuhn/libffi-stdlib-demo/commit/77deeca3dc171db5a9489983c36418474f0a425b
@623637646 maybe you could still fix this upstream, though? Thanks!

**Comment by 623637646** [comment]
Hi @DanielKuhn . Thanks for your feedback. It's fixed on version SwiftHook 3.5.2.

**Comment by netTrekHoffmann** [comment]
Hey @623637646 , I just stumbled across this issue after updating ImpressionKit - would it be possible to update the dependency of ImpressionKit to SwiftHook to also fix this issue there? Thanks in advance :)

**Comment by 623637646** [comment]
@netTrekHoffmann , Thank you for your feedback. Please upgrade ImpressionKit  to 3.7.6 to fix this issue.

**Comment by netTrekHoffmann** [comment]
Thank you very much
