### ISSUE TITLE
可以hook swift的struct吗

### ISSUE THREAD

**Issue by paradiseduo** [623637646/SwiftHook#6]

**Comment by 623637646** [comment]
SwiftHook是基于 iOS runtime 的。 不支持 hook swift的struct。

**Comment by 623637646** [comment]
<img width="950" alt="Screenshot 2021-04-22 at 2 10 27 PM" src="https://user-images.githubusercontent.com/5275802/115664508-82261600-a374-11eb-85a6-c6b6f64ee4fc.png">

Swift 不支持用`@objc`去修饰struct的方法。
