### ISSUE TITLE
真的很棒，但是他能支持swiftpackage吗,pod有bug

### ISSUE THREAD

**Issue by aadog** [623637646/SwiftHook#7]
真的很棒，但是他能支持swiftpackage吗,pod有bug

**Comment by 623637646** [comment]
谢谢你。

我试了下，现在SPM好像不支持一个swift package里面混合 swift和OC代码，[详见这里](https://joesusnick.medium.com/swift-package-manager-with-a-mixed-swift-and-objective-c-project-part-1-2-19fbb43d0460)。 

<img width="669" alt="Screenshot 2021-05-18 at 10 25 28 PM" src="https://user-images.githubusercontent.com/5275802/118669027-fb0b7700-b827-11eb-9b1b-c2c457f65003.png">

<img width="730" alt="Screenshot 2021-05-18 at 10 23 56 PM" src="https://user-images.githubusercontent.com/5275802/118669085-09599300-b828-11eb-9971-cc337c50578e.png">


你有什么好主意么？

**Comment by aadog** [comment]
对，我自己也尝试做了一个包也是这个错误，我刚学习swift一天，我看了似乎有一个Dynamic的包支持这样玩

**Comment by aadog** [comment]
你的代码里大量的工作都在做,原始参数替换，我做了十几个小时也是在处理这个问题，似乎很不好处理，别的框架都是提供一个签名然后用block来解决，有一个Dynamic的框架似乎可以处理这个但是我不熟悉swift https://github.com/mhdhejazi/Dynamic

**Comment by aadog** [comment]
安装了pod以后会出现gcc的init函数不调用的情况，你这个参数替换花了很大精力可以看的出来，如果需要我辅助操作随时待命

**Comment by aadog** [comment]
这是我最初想法，被你实现了
```
import Foundation

class HKContext{
    var ToIMP:IMP?
    var OldIMP:IMP?
    var ToMethod:Method?
//    func buildoldfn<T>(tp:T.Type)->T{
//        let sayHiTo:T = unsafeBitCast(self.OldIMP, to: tp.self)
//        return sayHiTo
//    }
}

@objc class hk:NSObject{
    static func getClassMethodIMP(_ tocls:AnyClass?,_ sel:Selector)->HKContext{
        let newMethod = class_getClassMethod(tocls, sel)!
        let newImplementation = method_getImplementation(newMethod)
        let hkctx=HKContext()
        hkctx.ToMethod=newMethod
        hkctx.ToIMP=newImplementation
        return hkctx
    }
    static func getClassInstanceMethodIMP(_ tocls:AnyClass?,_ sel:Selector)->HKContext{
        let newMethod = class_getInstanceMethod(tocls!, sel)!
        let newImplementation = method_getImplementation(newMethod)
        let hkctx=HKContext()
        hkctx.ToMethod=newMethod
        hkctx.ToIMP=newImplementation
        return hkctx
    }
    static func hookClassMethod(_ oldcls:AnyClass?,_ oldmethod:String,_ ctx:HKContext){
        let oldSelector = NSSelectorFromString(oldmethod)
        let oldMethod = class_getClassMethod(oldcls!, oldSelector)!
        let oldImp=class_getMethodImplementation(oldcls, oldSelector)
        ctx.OldIMP=oldImp
        method_setImplementation(oldMethod, ctx.ToIMP!)
//  
//        method_setImplementation(ctx.ToMethod!, ctx.OldIMP!)
    }
}
```

**Comment by 623637646** [comment]
非常感谢支持！ 欢迎提出宝贵意见建议。 这个issue我就先关了。

**Comment by 623637646** [comment]
For further progress, refer here: https://github.com/623637646/SwiftHook/issues/8

**Comment by 623637646** [comment]
Hi @a97077088 。 SPM is supported from 3.2.0
