### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by Alkenso** [623637646/SwiftHook#8]
Consider to add Swift Package Manager support for your cool library.

**Comment by 623637646** [comment]
Thanks, bro. I tried to do that but can't. 
I got this error.

![image](https://user-images.githubusercontent.com/5275802/121496610-36572b00-ca0d-11eb-9400-67fc7827837a.png)

I think swift package doesn't support mixing Swift and Objective-c code. Refer to [here](https://joesusnick.medium.com/swift-package-manager-with-a-mixed-swift-and-objective-c-project-part-1-2-19fbb43d0460)

![image](https://user-images.githubusercontent.com/5275802/121496572-2b9c9600-ca0d-11eb-88f4-9fa9552ca44b.png)

Correct me if I am wrong.

**Comment by Alkenso** [comment]
Yep, that's right

Seems you need to separate C sources into dependent SPM target

**Comment by 623637646** [comment]
I see. Thanks. 
Others also want to use this lib in SPM https://github.com/623637646/SwiftHook/issues/7
I am not familiar with SPM. I would appreciate if you could help to implement it and make a PR.

**Comment by 623637646** [comment]
~~I have investigated the solution. It's blocked by this issue: 
https://forums.swift.org/t/how-to-use-a-custom-build-configuration-in-a-swift-package/36259/18
Will continue this feature since the issue be fixed by Apple.~~

I am doing this feature.

**Comment by 623637646** [comment]
SPM is supported from 3.2.0. @Alkenso
